### ISSUE TITLE
Form items is readonly

### ISSUE THREAD

**Issue by windgaucho** [atanasster/grommet-controls#12]
Hello again, I am trying to use the form to edit data using the Form component with object property, but when I load the data from the database the form turns read only.

The same is happening with your sample here:
[https://grommet-nextjs.herokuapp.com/examples/grommet-controls/Form/object](https://grommet-nextjs.herokuapp.com/examples/grommet-controls/Form/object)
And also with this sample:
[https://grommet-nextjs.herokuapp.com/examples/grommet-controls/Form/profile](https://grommet-nextjs.herokuapp.com/examples/grommet-controls/Form/profile)
with this last one, the first time the page load it work as expected, but if you switch with other sample and back again, then the form turns readonly.

Any help would be much appreciated.

**Comment by windgaucho** [comment]
@atanasster Any hint on this?

**Comment by atanasster** [comment]
Sorry for taking longer than usual, i am currently in Europe and will try my best to look into it today or tomorrow.

**Comment by atanasster** [comment]
@windgaucho - sorry the delay was longer than I anticipated. It should now be fixed in grommet-controls 1.1.21. 
To fix it, I had to remove the usage of FormState and use the react hooks and state context.
Please let me know if have any issues with the new implementation
