### ISSUE TITLE
DateInput maskFormat and cal picking produce an error

### ISSUE THREAD

**Issue by cscognamiglio** [atanasster/grommet-controls#18]
If I specify an alternative maskFormat from the defaule, as in the example below, I get an error if I use the datepicker and I select a day that is above 12. If I select a day before 12 the date is in the wrong format (i.e. mm dd yyyy).

Manual input of the date with autocorrect enabled works correctly.

<DateInput placeholder="JJ/MM/AAAA" autocorrect={true}
                                           maskFormat="dd mm yyyy"
                                           locale="fr-FR" value={resource.date_to}
                                           onChange={({ target: { value } }) => this.handleChange('date_to', value)} />

The exception is not very meaningful, it happens in the MaskedInput component and it is:
TypeError: s is undefined

**Comment by cslash** [comment]
Any update on this? I can't use the datepicker with a DD/MM/YYYY format, no matter what I try. Even the example with the es locale on your website does not work

**Comment by atanasster** [comment]
No updates, sorry - I am pretty much going away from grommet.

Will try to keep the library updated but you can also submit a PR with a fix.

**Comment by leonardobork** [comment]
Same here. Anyone who wants to usse grommet, my tip is to go away. Has so many things missing
