### ISSUE TITLE
Error on Blank icon

### ISSUE THREAD

**Issue by windgaucho** [atanasster/grommet-controls#2]
Hello, great set of grommet controls !!

I installed the controls with npm in my project, but when I try to use some of them I am gettins the following error:

````
./node_modules/grommet-controls/es6/components/PagingTable/components/ThComponent.js
Module not found: Can't resolve 'grommet-icons/Blank' in '/Users/luis/desarrollo/nextjs/grommet-dashboard/node_modules/grommet-controls/es6/components/PagingTable/components'
````

I solved by copying the Blank.icon in the grommet-icons folder, but if install the components in another project the I am getting the same error.

I am doing something wrong?

**Comment by atanasster** [comment]
Hi @windgaucho , thanks a lot for the feedback. grommet-icons 3.2.0 was just released and changed the location of the `Blank` icon to fix some tree shaking issues and grommet-controls was out of sync for a day or two. 
Can you please now install the latest `"grommet-controls": "^0.90.8",` and let me know if you still have any issue.

**Comment by windgaucho** [comment]
Thank you @atanasster it work now.
