### ISSUE TITLE
Strorybook freezes when trying to switch between menu items

### ISSUE THREAD

**Issue by nomadus** [atanasster/grommet-controls#21]
Not sure, if this is happening to me, but when I switch from one menu item to another, the whole storybook freezes. It takes some time to recover.

**Comment by atanasster** [comment]
@nomadus - its not you, it takes a few seconds, depending on the component. 
I am developing a storybook dependencies plugin and the grommet-controls storybook site is my 'playground': https://github.com/atanasster/storybook-addon-deps/ . 
The plugin is in early stages and not much optimized. I will try to update it in the next couple of days

**Comment by atanasster** [comment]
this should be fixed now with a new version of the dependency plugin

**Comment by nomadus** [comment]
Thanks! It is OK now
