### ISSUE TITLE
Grommer Controls website is broken

### ISSUE THREAD

**Issue by dhfuzari** [atanasster/grommet-controls#26]
https://grommet-nextjs.herokuapp.com/

![grommet-controls](https://user-images.githubusercontent.com/2472221/71546814-be13bb80-2978-11ea-844a-421c035ccb8b.png)

**Comment by atanasster** [comment]
Hi thanks for reporting - the free dynos quota is exhausted on heroku, however the actual documentation site for grommet-controls is now:

https://atanasster.github.io/grommet-controls/?path=/story/controls-controls-avatar--main

**Comment by dhfuzari** [comment]
Thank you so much @atanasster.

**Comment by dhfuzari** [comment]
By the way, I'm using grommet-controls on two projects in my free time. If you need some help, contact me. I'm a front-end developer from Brazil, and I think I can help something. Good bye.

**Comment by atanasster** [comment]
Thanks! I definitely need some help as I am not using much grommet and nowadays keep grommet-controls just to test out storybook addons. You can check the open issues, or if you need any help on contributing let me know.
