### ISSUE TITLE
Documentation is dead

### ISSUE THREAD

**Issue by blur50** [atanasster/grommet-controls#29]
When entering https://grommet-nextjs.herokuapp.com, a heroku app error appears.

**Comment by atanasster** [comment]
Yes,sorry about that - my heroku free minutes expired for March.

In the meantime, you can get the documentation and examples here: https://atanasster.github.io/grommet-controls/?path=/story/docs-info-welcome--page

**Comment by blur50** [comment]
Thanks for the quick response!
I'll check out the docs in the link.
