### ISSUE TITLE
filterByFocusable is removed in grommet release 2.11

### ISSUE THREAD

**Issue by bartv2** [atanasster/grommet-controls#31]
`filterByFocusable` is used in the `Form` and `PagingTable` components. This makes at least the `Form` component unusable. It happened in PR https://github.com/grommet/grommet/pull/3650.

**Comment by atanasster** [comment]
Thanks for reporting. Its been a while since I am not using grommet and not following their PRs. Are you interested to submit a PR to address this issue?

**Comment by atanasster** [comment]
@bartv2 thanks for your PR, I just released 2.0.5 to npm

**Comment by bartv2** [comment]
Nice, thanks for the release

**Comment by atanasster** [comment]
Thanks for the PR, really appreciated it and it gave me some energy to massively update a version 3 (new typescript, linting) and most importantly with a new documentation site and automated tests with https://component-controls.com.

new docs: https://grommet-controls.netlify.app/docs/controls-avatar--main/test

new tests (magically using the already created 'stories'): https://github.com/atanasster/grommet-controls/blob/e48bff262025f50ae4f99fb28cccd7df02c39eaa/package.json#L40

**Comment by bartv2** [comment]
That looks like a really useful project, nice to know that exists
