### ISSUE TITLE
PagingTable Column decorations

### ISSUE THREAD

**Issue by windgaucho** [atanasster/grommet-controls#37]
Thank you very much for this library, very good work!!

I was using a previous version of grommet-controls and now I have updated to the last version and the column align cell decorations stop working.
This is part of the columns definition code:

```
....
{
   Header: 'Unit Price',
   accesor: 'price',
   decorations: {
     cell: {
       align: 'end',
     },
   },
},
.......
```
I am missing something?

**Comment by atanasster** [comment]
Hi @windgaucho , I am not using grommet for a long time now, but can you try 

```
decorations: {
  cell: {
    justify: 'end',
  },
},
```

**Comment by atanasster** [comment]
let me know if this is still an issue

**Comment by windgaucho** [comment]
Sory for the long delay, it work ok!!
