### ISSUE TITLE
PagingTable, bottom page number button and input text is not working as expected

### ISSUE THREAD

**Issue by DreamerIn** [atanasster/grommet-controls#38]
![image](https://user-images.githubusercontent.com/34124341/124438369-b74bdd00-dd95-11eb-80d8-4937bea97aac.png)

Expected result
1. OnChange of Page number in the input text, it has to update the page number.
2. OnClick of + or - icon it should increase or decrease the page number.
These above are not working.

**Comment by DreamerIn** [comment]
I have a work around for this, let me know, that I have to create PR for this.

**Comment by atanasster** [comment]
@DreamerIn - a PR would be fantastic, thanks

**Comment by DreamerIn** [comment]
@atanasster I have created a PR, https://github.com/atanasster/grommet-controls/pull/39. Please have a look and suggest.

**Comment by atanasster** [comment]
Thanks @DreamerIn just published 3.0.2 with your change

**Comment by DreamerIn** [comment]
> Thanks @DreamerIn just published 3.0.2 with your change

Thanks you🙂
