### ISSUE TITLE
Error after an install and trying to use

### ISSUE THREAD

**Issue by nomadus** [atanasster/grommet-controls#4]
Hi,
I installed grommet-controls and when I tried to use it I got the following issue.

./node_modules/grommet-controls/es6/components/BarChart/BarChart.js
Module not found: Can't resolve 'react-chartjs-2' in 'C:\src\test\node_modules\grommet-controls\es6\components\BarChart'

**Comment by atanasster** [comment]
Hi, it seems you do not have tree shaking set up in place, so the whole,library is being pulled into your project.

If you have trouble setting up,tree shaking, you will need to import the required component from its own folder, something like
`Import { NumberInput } from ‘grommet-controls/componnets/NumberInput’;`

**Comment by nomadus** [comment]
Thanks, it works.

**Comment by atanasster** [comment]
Cool, closing this but please keep in mind that your project is probably pulling in the entire grommet / vrommet-icons library since teee shaking seems not enabled.
