### ISSUE TITLE
Can't enter a number with fractional parts

### ISSUE THREAD

**Issue by nomadus** [atanasster/grommet-controls#5]
Hi,
I am testing NumberInput and I can't enter fractional digits from the keyboard. When I copy and paste it works. What's the expected behavior here?

**Comment by atanasster** [comment]
Hi

You probably need to set the decimals property, here is a sample

https://grommet-nextjs.herokuapp.com/examples/grommet-controls/NumberInput/decimals


Also more documentation
https://grommet-nextjs.herokuapp.com/documentation/grommet-controls/NumberInput

**Comment by nomadus** [comment]
I tried with the link you provided and tried to enter a number with a fractional part, it does not take the dot

**Comment by atanasster** [comment]
Sorry, I am on the road and didn't have the time to try, It seems something is slightly off, but can you please update in the following way. I will also check why it didn't take it by default.
<NumberInput
updateToString={true}
...
/>

**Comment by atanasster** [comment]
@nomadus released a new version 1.0.11 - please update and by default the decimals will work. There was an issue with my attempt to update the value as a number instead of a string

https://grommet-nextjs.herokuapp.com/examples/grommet-controls/NumberInput/decimals

**Comment by atanasster** [comment]
closing this, let me know if you couldn't make it work

**Comment by nomadus** [comment]
Hi, I somehow hit this issue again, the version I am using is  "grommet-controls": "^1.1.21",

**Comment by atanasster** [comment]
Hi @nomadus 

I just tried to enter 3.555 at the decimals example here https://grommet-nextjs.herokuapp.com/documentation/grommet-controls/NumberInput

And it seems to work fine. How can I reproduce your issue?

**Comment by nomadus** [comment]
Hi, I created new app and could not reproduce the issue, I can enter the number with the decimals. I wonder what's wrong with my existing codebase. Let me have another look.

**Comment by atanasster** [comment]
thanks, let me know.

**Comment by nomadus** [comment]
This happens when I try to submit the form, where I have a NumberInput. The message is "Please match the requested format", I guess this is a builtin validation, which I turned off by adding novalidate to the form component. This resolved the issue.

**Comment by atanasster** [comment]
If you have a chance, can you please post a sample that reproduces the situation - not sure if its a bug or not.
