### ISSUE TITLE
Heroku demo page gets a 500 error when following link from github

### ISSUE THREAD

**Issue by DanielBaird** [atanasster/grommet-controls#6]
If I go to https://grommet-nextjs.herokuapp.com/ and click Controls, I get to https://grommet-nextjs.herokuapp.com/add-ons and it's a working page with controls showing on it.

However if I click the link from the github repo, or if I paste the add-ons url into a browser, I get a 500 error page.

Weird, right?

**Comment by atanasster** [comment]
Thanks, seems i introduced some issues with the site, working on a significant update and will get it fixed asap

**Comment by atanasster** [comment]
Fixed it, but had to upload my WIP changes to the site
