### ISSUE TITLE
Is there support for selected/onSelected behavior for PagingTable?

### ISSUE THREAD

**Issue by eoliphan** [atanasster/grommet-controls#7]
It's generally nice to have a ability to select a row, such that there's visual feedback, complemented by some sort of onSelect callback, and possibly even a 'selected' field that returns the backing object/index/etc of the selected row.

**Comment by atanasster** [comment]
Hi @eoliphan sorry for leaving this issue open for so long. I am now mostly using the devexpress react grid : https://devexpress.github.io/devextreme-reactive/react/grid/

Here is an example for select: http://grommet-nextjs.herokuapp.com/template/dx-grid/selection%2Fselect-all-paging

and more examples here http://grommet-nextjs.herokuapp.com/templates/dx-grid
