### ISSUE TITLE
How to make a customized <Card /> reusable?

### ISSUE THREAD

**Issue by midnightcodr** [atanasster/grommet-controls#8]
Hi, suppose I want to customize all my `<Card />` components to have the following
properties:
```
    background='brand'
    border={{ color: 'card' }}
    elevation='none
```

How can I do that without repeating myself by injecting those attributes to all my `<Card />` components? I am attempting to do something like the following
```jsx
// Card.js
import React from 'react'
import { Card } from 'grommet-controls'

export default props => (
  <Card background='brand' elevation='none' border={{ color: 'card' }}>
    {props.children}
  </Card>
)
```

Then I can import Card from `Card.js` instead of 'grommet-controls' but then I loss access to all the Card.* sub components that comes with 'grommet-controls'. I am thinking about using HOC but not sure how to do that. Please advise. Thanks.

**Comment by atanasster** [comment]
Hi,

I think you can export the additional sub componnets the same way from your own file
export const MyCard = …
MyCard.CardTitle = Card.CardTitle

**Comment by midnightcodr** [comment]
I ended up doing something like this instead
```jsx
import React from 'react'
import { Card } from 'grommet-controls'

const MyCard = props => (
  <Card background='brand' elevation='none' border={{ color: 'card' }}>
    {props.children}
  </Card>
)

export { MyCard, Card }

```


in places where I need to import
```js
import { MyCard, Card } form './Card'
```
