### ISSUE TITLE
ReactTable needs to pass className for styled-components?

### ISSUE THREAD

**Issue by joshball** [atanasster/grommet-controls#9]
I noticed the following warning in the console when using PagingTable:

`It looks like you've wrapped styled() around your React component (ReactTable), but the className prop is not being passed down to a child. No styles will be rendered unless className is composed within your React component.`

The [styled-components docs say](https://www.styled-components.com/docs/basics#styling-any-components) :

> The styled method works perfectly on all of your own or any third-party components, as long as they attach the passed `className` prop to a DOM element.

I started poking around `ReactTable`, and because it is an aggregation of so many table components, it is not inherently obvious to me where to place this. 

Any thoughts on this?

**Comment by atanasster** [comment]
hi @joshball thanks for noticing this. It should now be fixed in 1.1.19 - please install the new version and let me know if you still see the issue
